version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Admin123
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    volumes:
       - fastapi_sqlalchemy_alembic_db:/data/postgres
    networks:
      - fastapi_sqlalchemy_alembic

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: Admin123
    ports:
      - "5433:80"
    networks:
      - fastapi_sqlalchemy_alembic

networks:
  fastapi_sqlalchemy_alembic:
    driver: bridge

volumes:
  fastapi_sqlalchemy_alembic_db:

